v1.0.0

diff --git a/.github/workflows/publishGitHubPackages.yml b/.github/workflows/publishGitHubPackages.yml
--- a/.github/workflows/publishGitHubPackages.yml
+++ b/.github/workflows/publishGitHubPackages.yml
@@ -24,8 +24,20 @@ jobs:
         uses: actions/checkout@v3
         
       - name: Extract version from commit message
-        id: version
-        run: echo ::set-output name=version::$(echo "$GITHUB_REF" | sed -n 's/.*\///p' | sed -n 's/v//p')
+        run: |
+          # Get the latest commit message
+          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+
+          # Extract the version from the commit message
+          # assuming the version is in the format v1.0.0
+          REGEX="v[0-9]+\.[0-9]+\.[0-9]+"
+          if [[ $COMMIT_MESSAGE =~ $REGEX ]]; then
+          export VERSION="${BASH_REMATCH[0]}"
+          else
+          echo "Error: Version not found in the commit message"
+          exit 1
+          fi
+          echo "Version: $VERSION"
           
       - name: Log in to the Container registry
         uses: docker/login-action@v2
