publishGitHubPackages

diff --git a/.github/workflows/publishGitHubPackages.yml b/.github/workflows/publishGitHubPackages.yml
--- a/.github/workflows/publishGitHubPackages.yml
+++ b/.github/workflows/publishGitHubPackages.yml
@@ -47,8 +47,8 @@ jobs:
           
       - name: Set image version
         id: set-version
-        run: echo ::set-env name=IMAGE_VERSION::$(cat Version.txt)
+        run: echo ::set-env name=IMAGE_VERSION::$(cat Version.txt) 
       - name: Build Docker Image
         run: |
-          docker build . --tag ghcr.io/marinosefstathiou/firstimage:${MY_VERSION}
-          docker push ghcr.io/marinosefstathiou/firstimage:${MY_VERSION}
+          docker build . --tag ghcr.io/marinosefstathiou/firstimage:${MY_VERSION} || echo "Error: Version not found in the commit message docker build will not execute"
+          docker push ghcr.io/marinosefstathiou/firstimage:${MY_VERSION} || echo "Error: Version not found in the commit message docker push will not execute"
